#cloud-config
package_update: true

runcmd:
  
  - sudo apt install --reinstall -y linux-modules-extra-$(uname -r)
  - sudo apt install libibverbs1 ibverbs-utils librdmacm1 libibumad3 ibverbs-providers rdma-core gdb perftest libpcap-dev libyaml-cpp-dev
  - sudo modprobe rdma_rxe